POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
    "username": "test@sukjuhong.io",
    "password": "testpassword"
}

###

POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "username": "test@sukjuhong.io",
    "password": "testpassword"
}